-- DCM's fixed one-line condition + action text, keyed by QRH procedure
-- title (the exact string a `PROC:` line names — docs/doctor-qrh.md).
-- fetch_doctor.sh emits `proc` plus a dynamic `detail`; the words shown on
-- screen live here, not in the provider. Every string is uppercase (the data
-- font has no lowercase glyphs) and short enough for one 448px DCM line.
--
--   cond   static condition line, or a function(detail) -> string
--   label  action line, left half  ("-LABEL......VALUE")
--   value  action line, right half (string, or function(detail) -> string)
--
-- Keep in step with the QRH: a new procedure there needs a row here (a proc
-- with no row still renders, as "SEE QRH" plus the title).
local T = {}

local function e(proc, cond, label, value)
  T[proc] = { cond = cond, label = label, value = value }
end

local function detail(prefix)
  return function(d)
    d = (d or ""):upper()
    if d == "" then return prefix end
    return prefix .. ": " .. d
  end
end

-- GENERIC
e("PROFILE TOML MISSING", "PROFILE TOML MISSING", "RERUN BOOTSTRAP", "BIN/GTEX62-CORE-BOOTSTRAP-RUNTIME")
e("DOMAIN NOT LISTED", "ENABLED IN CORE.TOML, NOT IN [DOMAINS]", "ADD TO [DOMAINS]", "SUITES/DOCTOR.TOML")
e("FALLBACK TTL", "PROFILE LACKS TTL KEY - DEFAULT CADENCE", "ADD KEY, RESTART SUITE", function(d) return (d or "PROFILE TOML"):upper() end)
e("PROVIDER STALE", "CACHE PAST TTL, PROVIDER REPORTS OK", "CHECK API KEY, NETWORK", "REACHABILITY")
e("CONFIG VALUE UNSET", "CONFIG VALUE UNSET", "EDIT FILE, SET VARIABLE", "SEE ENTRY")
e("UNRECOGNIZED NOTE", detail("UNRECOGNIZED NOTE"), "READ NOTE", "STATUS.JSON")

-- AIR
e("AIR COORDINATES MISSING", "AIR COORDINATES MISSING", "SET [LOCATION] LAT/LON", "AIR PROFILE, SITE.TOML")
e("AIR API KEY MISSING", "AIR API KEY MISSING", "SET API KEY", "AIR PROFILE")
e("AIR NO CACHE", "AIR HAS NO CACHE", "CHECK REACHABILITY", "OPENWEATHER, AIRNOW")
e("AIR NO TIMESTAMP", "AIR CACHE HAS NO PROVIDER TIMESTAMP", "CHECK API STATUS", "AIRNOW, OPENWEATHER")
e("AIR OPENWEATHER DEGRADED", "OPENWEATHER AQI SOURCE DOWN", "CHECK API KEY, QUOTA", "OPENWEATHER")
e("AIR AIRNOW DEGRADED", "AIRNOW AQI SOURCE DOWN", "CHECK API KEY, QUOTA", "AIRNOW")

-- ALERTS
e("ALERTS NOT RUNNING", "ALERTS PROVIDER NOT RUNNING", "FETCH_ALERTS.SH", "IN REFRESH LOOP")

-- AP
e("AP NO IPS CONFIGURED", "NO AP IPS CONFIGURED", "SET [AP] IPS/LABELS", "SITE.TOML")
e("AP PASSWORD FILE MISSING", "AP PASSWORD FILE NOT FOUND", "CREATE FILE", "~/.CONFIG/ZYXEL_AP/.PASS")
e("AP SSH GATE", "AP SSH GATE TRIPPED", "CHECK SSH ALIAS, SSHPASS", "AP")

-- ASTRO
e("ASTRO LOCATION MISSING", "ASTRO LOCATION MISSING", "SET [LOCATION] LAT/LON", "ASTRO PROFILE, SITE.TOML")
e("ASTRO FALLBACK TTL", "ASTRO PROFILE HAS NO [CACHE] SECTION", "ADD [CACHE], RESTART SUITE", "ASTRO PROFILE")

-- AVIATION
e("AVIATION DEGRADED", detail("AVIATION DEGRADED"), "SERVING CACHED DATA", "CHECK AVIATIONWEATHER.GOV")
e("AVIATION NO CACHE", "AVIATION HAS NO CACHE", "CHECK REACHABILITY", "AVIATIONWEATHER.GOV")

-- CALENDAR
e("CALENDAR NEVER RUN", "CALENDAR HAS NEVER RUN", "CHECK REFRESH_LOOP WIRING", "INITIAL_REFRESH")

-- CONNECT
e("CONNECT SPEEDTEST FAILING", "SPEEDTEST FAILING", "CHECK SPEEDTEST CLI", "INSTALLED, LICENSED")
e("CONNECT SPEEDTEST STALE", function(d) return "NO SPEEDTEST IN " .. ((d or ""):upper()) end, "RUN SPEEDTEST", "MANUALLY")

-- GITHUB
e("GITHUB REGISTRY EMPTY", "REPO REGISTRY EMPTY", "POPULATE FILE", "~/.CONFIG/CONKY/GITHUB-TRAFFIC-REPOS.JSON")
e("GITHUB FETCH FAILING", detail("FETCH FAILING"), "CHECK AUTH", "GH AUTH STATUS")
e("GITHUB NEVER RUN", "GITHUB HAS NEVER RUN", "CHECK TIMER", "GTEX62-GITHUB-TRAFFIC.TIMER")
e("GITHUB REFRESH", function(d) return "TRAFFIC COPY " .. ((d or ""):upper()) .. " DAYS BEHIND" end, "START SERVICE NOW", "GTEX62-GITHUB-TRAFFIC.SERVICE")

-- MEDIA
e("MEDIA LOCAL DIR UNREACHABLE", "LYRICS LOCAL_DIR UNREACHABLE", "CHECK NAS MOUNT", "[MEDIA.LYRICS] LOCAL_DIR")

-- MODEM
e("MODEM PASSWORD NOT SET", "MODEM PASSWORD NOT CONFIGURED", "SET [CREDENTIALS].PASSWORD", "MODEM PROFILE")
e("MODEM UNREACHABLE", "MODEM UNREACHABLE", "CHECK PFSENSE NAT PATH", "192.168.100.1")
e("MODEM AUTH FAILED", "MODEM AUTH FAILED", "CHECK CREDENTIALS", "[CREDENTIALS].PASSWORD")
e("MODEM CONN DEGRADED", "MODEM NOT REGISTERED WITH COMCAST", "CHECK DOCSIS SYNC", "NOT THE SCRAPER")
e("MODEM HEADER MAPPING", "MODEM ADMIN UI LAYOUT MAY HAVE CHANGED", "READ CHANNEL-TABLE NOTE", "MODEM STATUS")
e("MODEM NO UPSTREAM LOCK", "NO LOCKED UPSTREAM CHANNELS", "CHECK DOCSIS UPSTREAM SYNC", "MODEM")

-- MTR
e("MTR NO SSH TARGET", "MTR HAS NO SSH TARGET", "SET SSH_TARGET", "MTR PROFILE")
e("MTR SSH GATE", "MTR SSH GATE TRIPPED", "CHECK SSH ALIAS, SSHPASS", "MTR (PI5)")

-- NET
e("NET FALLBACK TTL", "NET ON 60S FALLBACK CADENCE, NOT 1S", "RERUN BOOTSTRAP, RESTART", "BIN/GTEX62-CORE-BOOTSTRAP-RUNTIME")
e("NET NOT RUNNING", "NET PROVIDER NOT RUNNING", "CHECK REFRESH_LOOP", "ALIVE")

-- NETWORK
e("NETWORK NULL FIELDS", detail("NETWORK"), "CHECK PRIMARY_INTERFACE", "NETWORK PROFILE")

-- ORB
e("ORB FALLBACK TTL", "ORB PROFILE HAS NO [CACHE] TTL_SEC", "RERUN BOOTSTRAP, RESTART", "BIN/GTEX62-CORE-BOOTSTRAP-RUNTIME")

-- PFSENSE
e("PFSENSE NO SSH TARGET", "PFSENSE HAS NO SSH TARGET", "SET SSH_TARGET", "PFSENSE PROFILE")
e("PFSENSE SSH GATE", "PFSENSE SSH GATE TRIPPED", "CHECK SSH ALIAS, SSHPASS", "PFSENSE")
e("PFSENSE SUBCACHE STALE", detail("SUB-CACHE STALE"), "IDENTIFY SUB-CACHE", "SEE ENTRY")
e("PFSENSE SUBCACHE DEGRADED", detail("SUB-CACHE"), "READ SUB-CACHE NOTE", "SHARED/PFSENSE")

-- PIHOLE
e("PIHOLE NO SSH TARGET", "PIHOLE HAS NO SSH TARGET", "SET [PIHOLE] SSH_TARGET", "PFSENSE PROFILE")
e("PIHOLE SSH GATE", "PIHOLE SSH GATE TRIPPED", "CHECK SSH ALIAS, SSHPASS", "PIHOLE (PI5)")

-- SOLAR
e("SOLAR WAITING", "SOLAR WAITING ON WEATHER CACHE", "CHECK ROW", "WEATHER")

-- SYSTEM / TIME
e("SYSTEM NOT RUNNING", "SYSTEM PROVIDER NOT RUNNING", "CHECK REFRESH_LOOP", "ALIVE")
e("TIME NOT RUNNING", "TIME PROVIDER NOT RUNNING", "CHECK REFRESH_LOOP", "ALIVE")

-- VPN
e("VPN PIACTL MISSING", "PIACTL NOT FOUND", "PIA CLIENT", "INSTALLED, ON PATH")
e("VPN WG STATS DEGRADED", "WIREGUARD STATS UNAVAILABLE", "CHECK SUDOERS RULE", "/ETC/SUDOERS.D/GTEX62-CORE-VPN")
e("VPN TUNNEL PING DEGRADED", "VPN TUNNEL PING FAILING", "CHECK TUNNEL ROUTING", "VPN")

-- WEATHER
e("WEATHER CONFIG MISSING", "WEATHER CREDENTIALS/COORDINATES MISSING", "SET API KEY, LAT/LON", "WEATHER PROFILE")
e("WEATHER DEGRADED", detail("WEATHER DEGRADED"), "SERVING CACHED DATA", "CHECK OPENWEATHER")
e("WEATHER NO CACHE", "WEATHER HAS NO CACHE", "CHECK REACHABILITY", "OPENWEATHER")

local M = { table = T }

-- {cond, label, value} for an entry ({proc, detail, tag, domain}); an
-- unmapped proc still yields a usable pointer at the QRH.
function M.text(entry)
  local row = T[entry.proc or ""]
  if not row then
    return {
      cond = ((entry.detail or entry.tag or ""):upper()),
      label = "SEE QRH",
      value = (entry.proc or "UNRECOGNIZED NOTE"),
    }
  end
  local cond = row.cond
  if type(cond) == "function" then cond = cond(entry.detail) end
  local value = row.value
  if type(value) == "function" then value = value(entry.detail) end
  return { cond = cond, label = row.label, value = value }
end

return M
